# Generated by Django 3.2.6 on 2021-09-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name'], 'verbose_name': 'enlace', 'verbose_name_plural': 'enlaces'},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='urls',
            new_name='url',
        ),
    ]
